url: https://rubysec.com
title: RubySec
subtitle: Providing security resources for the Ruby community
author: RubySec
simple_search: https://www.google.com/search
description: Advisory database of security vulnerabilities found in Ruby projects

exclude:
  [
    .bundle,
    .github,
    _advisories,
    CNAME,
    Gemfile,
    Rakefile,
    README.md,
    vendor,
  ]

plugins:
  - jekyll-paginate

subscribe_rss: /atom.xml

permalink: /advisories/:title/
category_dir: advisories/categories

paginate: 10                    # Posts per page on the blog index
pagination_dir: advisories      # Directory base for pagination URLs eg. /blog/page/2/
recent_posts: 5                 # Posts in the sidebar Recent Posts section
excerpt_link: "Read on &rarr;"  # "Continue reading" link text at the bottom of excerpted articles

titlecase: false       # Converts page and post titles to titlecase

twitter_user: rubysec
twitter_tweet_button: true

github_repo: rubysec/rubysec.github.io

google_analytics: G-P90QEESFMF
